version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    container_name: elasticsearch-storage
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch-data:/media/sf_Shared/Бакаев/Elasticsearch/volume/data
    ports:
      - 9200:9200
  kibana:
    container_name: kibana-storage
    image: docker.elastic.co/kibana/kibana:8.4.3
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  storage:    
    container_name: storage
    image: storage:ubuntu20.04
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - LOCAL_STORAGE_DIR=/app/data/media
      - ELASTIC_URL=http://elasticsearch:9200
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - TEMPORARY_FILES_DIR=/app/data/media/temp
      - TEMPORARY_FILES_REMOVE_SCHEDULE_TIME=${TEMPORARY_FILES_REMOVE_SCHEDULE_TIME}
      - TEMPORARY_FILE_MAX_AGE=${TEMPORARY_FILE_MAX_AGE}
    ports:
      - "5011:80"
    volumes:
      - ${LOCAL_STORAGE_DIR}:/app/data
    depends_on:
      - elasticsearch
  nginx:
    container_name: nginx-storage
    image: nginx:alpine
    ports:
      - "5080:80"
    volumes:
      - ${LOCAL_STORAGE_DIR}:/usr/share/nginx/html
    depends_on:
      - storage